### ISSUE TITLE
Exercism CLI has been bumped to Version 2.4.0 in March '17

### ISSUE THREAD

**Issue by NobbZ** [Spinarooni/chocolatey-packages#1]
Also there is now a banner on the page users with older clients asking them to update. Due to limitations of a windows system it is not poossible to update the client through itself, neither is it possible to dismiss the banner permanently, so for users of the choco installed exercism-cli, there is currently no way to get rid of that banner.

Could you please bump the package and try to keep it updated or at least get in contact with the exercism-cli team to talk about future maintenance of the package?

**Comment by Spinarooni** [comment]
@NobbZ I'm in the process of updating the package now.  Thanks for the heads up.

**Comment by NobbZ** [comment]
I've seen its already enqueued for approval in the package index.

So please don't mind when I ask again, if you will be able to keep it up to date on your own or if you will reach out the team around the CLI to talk about the future of the package?

**Comment by Spinarooni** [comment]
I'll be updating it.  It just slipped under my radar as I have had many things going on.  My apologies.

**Comment by NobbZ** [comment]
Perhaps https://releaser.richardhagen.no/ helps?

I've set up a reminder for the exercism-cli there by myself as well as many other repositories to keep my personal gentoo-overlay up to date.
